file_format: "1"
id: itemun
name: itemun
type: shield
url: https://github.com/MartinDrillon/zmk-config
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - itemun_left
  - itemun_right