file_format: "1"
id: itemdeux
name: itemdeux
type: shield
url: https://github.com/MartinDrillon/zmk-config
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - itemdeux_left
  - itemdeux_right